COLOR_PLACEHOLDER = (150,150,150)

MINI_STICKER_AREA_TITLE_SIZE = 14
MINI_STICKER_AREA_TITLE_GAP = 2
MINI_STICKER_AREA_OFFSET = 20

STICKER_AREA_TITLE_SIZE =30 
STICKER_AREA_TITLE_GAP = 4
STICKER_AREA_OFFSET = 20

STICKER_CONTOUR_COLOR = (36,252, 12)
CALIBRATE_MODE_KEY = 'c'
SWITCH_LANGUAGE_KEY = 'l'
TEXT_SIZE = 18

CUBE_PALETTE = 'cube_palete'